name: AdvancedSearchExample
description: An example to show how the package works.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  advanced_search:
    path: /Users/muhammedrefaat/projects/advanced_search

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true